config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get '/waypoints', to: 'waypoints#index'
  get '/vehicle', to: 'vehicles#new'
  post '/api/v1/gps', to: 'vehicles#create'
  get  '/show', to: 'vehicles#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord

    self.primary_key = "vehicle_identifier"
    has_many :waypoints

    #validation que exista el parametro
    validates_presence_of :vehicle_identifier

    accepts_nested_attributes_for :waypoints, allow_destroy: true
   
    scope :lastGPS, -> {
        Vehicle.find_by_sql(
            "select t1.vehicle_id, t1.latitude, t1.longitude, t1.sent_at
            from waypoints t1
            inner join
            (
            select max(waypoints.sent_at) as maxdate, waypoints.vehicle_id
            from waypoints
            group by waypoints.vehicle_id
            ) t2
            on t1.vehicle_id = t2.vehicle_id
            and t1.sent_at = t2.maxdate"
        )
    }
end

app/models/waypoint.rb
class Waypoint < ApplicationRecord
  belongs_to :vehicle
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    vehicle = Vehicle.where(vehicle_identifier: vehicle_params[:vehicle_identifier])
                      .first_or_initialize
    vehicle.waypoints.build(vehicle_params[:waypoints])
    if vehicle.save
      render json: { msg: 'vehicle has been created', status: :created}
    else
      render json: { msg: "error #{vehicle.errors}", status: :unprocessable_entity}
    end
  end

  def show
    @vehicles = Vehicle.lastGPS
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(
      :vehicle_identifier,
      waypoints: %i[latitude longitude sent_at _destroy])
  end
end

app/controllers/waypoints_controller.rb
class WaypointsController < ApplicationController
    skip_before_action :verify_authenticity_token
    
    def index
        @waypoints = Waypoint.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/helpers/waypoints_helper.rb
module WaypointsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Waypoints</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.5.1/dist/leaflet.css"
   integrity="sha512-xwE/Az9zrjBIphAcBb3F6JVqxf46+CDLwfLMHloNu6KEQCAWi6HcDUbeOfBIptF7tcCzusKFjFw2yuvEpDL9wQ=="
   crossorigin=""/>
   <script src="https://unpkg.com/leaflet@1.5.1/dist/leaflet.js"
   integrity="sha512-GffPMF3RvMeYyc1LWMHtK8EbPv0iNZ8/oTtHPx9/cc2ILxQ+u905qIwdpULaqDkyBKgOaB57QTMg7ztg8Jm2Og=="
   crossorigin=""></script>

  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">Waypoints</span>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item active">
              <a class="nav-link" href="<%= vehicle_path %>">Agregar<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= waypoints_path %>">Todos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= show_path %>">Recientes</a>
            </li>
          </ul>
        </div>
      </nav>
    </header>
    <%= yield %>
  </body>
</html>

app/views/vehicles/new.html.erb
<div class="container">
    <br>
    <div class="row">
        <div class="col-md-12">
            <div id='mapid' style="width: 800px; height: 300px; border: 1px solid #AAA;"></div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-8">
            <%= form_with url: api_v1_gps_path, remote: true, html: {id: "vehicle-form"} do |f| %>
                <div class="form-group row">
                    <div class="form-group col-md-6">
                        <label for="inputlatitude">Latitud</label>
                        <input type="text" class="form-control" id="inputlatitude" name="latitude" readonly>
                    </div>
                    <div class="form-group col-md-6">
                        <label for="inputLongitude">Longitud</label>
                        <input type="text" class="form-control" id="inputLongitude" name="longitude" readonly>
                    </div>
                </div>
                <div class="form-group row">
                    <label for="inputVehicleId" class="col-sm-2 col-form-label">Placa Patente</label>
                    <div class="col-sm-10">
                        <input type="text" class="form-control" id="inputVehicleId" placeholder="Placa Patente" name="vehicle_identifier" required>
                    </div>
                    <input type="hidden" class="form-control" id="inputSent_at" name="sent_at">
                </div>
                <div class="form-group row">
                    <div class="col-sm-12">
                        <div class="text-right">
                            <button type="button" onclick="submitFrmAjax();" class="btn btn-outline-success btn-sm">Agregar Ubicación</button>
                            <%= link_to 'Ver Ubicaciones', waypoints_path, :class => "btn btn-outline-secondary btn-sm"%>
                            <%= link_to 'Ubicaciones Recientes', show_path, :class => "btn btn-outline-info btn-sm"%>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

<script>
    var mymap = L.map('mapid').setView([-33.4626533, -70.6804048], 10);

    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.streets',
        accessToken: 'pk.eyJ1IjoiaGdhbHZlejEwIiwiYSI6ImNqdnpqbnh0aDAxMnk0OG9uMnV0dnNzMGQifQ.g9JcGr0YRkDWaJ4TtkF94A'
    }).addTo(mymap);

    var popup = L.popup();

    function onMapClick(e) {
        let current_datetime = new Date()
        let formatted_date = current_datetime.getFullYear() + "-" + (current_datetime.getMonth() + 1) + "-" + current_datetime.getDate() + " " + current_datetime.getHours() + ":" + current_datetime.getMinutes() + ":" + current_datetime.getSeconds()
        popup
            .setLatLng(e.latlng)
            .setContent("You clicked the map at " + e.latlng.toString())
            .openOn(mymap);
        
        document.getElementById('inputlatitude').value = e.latlng.lat;
        document.getElementById('inputLongitude').value = e.latlng.lng;
        document.getElementById('inputSent_at').value = formatted_date;
    }

    mymap.on('click', onMapClick);
</script>
<script>
    function submitFrmAjax(){
        $.ajax({
            type: "POST",
            url: "/api/v1/gps",
            dataType: 'json',
            contentType: 'application/json',
            data: JSON.stringify({vehicle: {
                vehicle_identifier: $("#inputVehicleId").val(),
                waypoints: [{
                    latitude: $("#inputlatitude").val(),
                    longitude: $("#inputLongitude").val(),
                    sent_at: $("#inputSent_at").val()
                    }]
                }
            }),
            success: function (response) {
                document.getElementById("inputVehicleId").value = "";
                swal(response.status, response.msg, "success");
            },
            error: function (response) {
                swal(response.status, response.msg, "error");
            },
        });
    }
</script>

app/views/vehicles/show.html.erb
<div class="container">
    <br>
    <div align="center" class="row">
        <div class="col-md-12">
            <div id='mapid' style="width: 1000px; height: 300px; border: 1px solid #AAA;"></div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="card-body">
            <table id="table" class="table" >
                <thead>
                    <th>Placa Patente</th>
                    <th>Longitud</th>
                    <th>Latitud</th>
                    <th>Última conexión</th>
                </thead>
                <tbody>
                    <% @vehicles.each do |vehicle|  %>
                    <tr>
                        <td><%= vehicle.vehicle_id %></td>
                        <td><%= vehicle.latitude %></td>
                        <td><%= vehicle.longitude %></td>
                        <td><%= vehicle.sent_at %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    var mymap = L.map('mapid').setView([1.0302758, 34.3550684], 2);

    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}', {
        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
        maxZoom: 18,
        id: 'mapbox.streets',
        accessToken: 'pk.eyJ1IjoiaGdhbHZlejEwIiwiYSI6ImNqdnpqbnh0aDAxMnk0OG9uMnV0dnNzMGQifQ.g9JcGr0YRkDWaJ4TtkF94A'
    }).addTo(mymap);
    var obj = <%= @vehicles.to_json.html_safe %>;

    for ( var i=0; i < obj.length; ++i )
    {
        L.marker( [obj[i].latitude, obj[i].longitude])
        .bindPopup( "<b>Placa Patente</b><br><center>" + obj[i].vehicle_id + "</center>" )
        .addTo( mymap );
    }
</script>

app/views/waypoints/index.html.erb
<div class="container">
    <h3> Todas las ubicaciones <%= link_to 'Agregar', vehicle_path, :class => " btn btn-sm btn-outline-primary"%></h3>
    <div class="row">
        <div class="card-body">
            <table id="table" class="table" >
                <thead>
                    <th>Placa Patente</th>
                    <th>Longitud</th>
                    <th>Latitud</th>
                    <th>Última conexión</th>
                </thead>
                <tbody>
                    <% @waypoints.each do |waypoint|  %>
                    <tr>
                        <td><%= waypoint.vehicle_id %></td>
                        <td><%= waypoint.latitude %></td>
                        <td><%= waypoint.longitude %></td>
                        <td><%= waypoint.sent_at %></td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
    </div>
</div>